[package]
name = "sfsm"
version = "0.1.0"
authors = ["Samuel Schuepbach <schuepbs@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sfsm-base = {path = '../sfsm-base'}
sfsm-proc = {path = '../sfsm-proc'}