[package]
name = "sfsm"
version = "0.2.1"
authors = ["Samuel Schuepbach <schuepbs@gmail.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"
keywords = ["static", "state-machine", "no_std", "embedded"]
repository = "https://gitlab.com/sfsm/sfsm"
description = "Generate static state machines"

[dependencies]
sfsm-base = "0.1.2"
sfsm-proc = "0.2.2"
