[package]
name = "sfsm"
version = "0.1.0"
authors = ["Samuel Schuepbach <schuepbs@gmail.com>"]
edition = "2018"
license-file = "LICENSE"
readme = "README.rst"
keywords = ["static", "state-machine", "no_std", "embedded"]
repository = "https://gitlab.com/sfsm/sfsm"
description = "Generate static state machines"

[dependencies]
sfsm-base = "0.1.0"
sfsm-proc = "0.1.0"